# Generated by Django 3.1.1 on 2020-09-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emali', models.CharField(max_length=100)),
                ('is_send', models.BooleanField(verbose_name='是否发送')),
            ],
            options={
                'verbose_name': '邮箱管理',
                'verbose_name_plural': '3.邮箱管理',
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, max_length=10)),
                ('updateTime', models.DateTimeField(auto_now=True, verbose_name='updateTime')),
                ('is_send', models.BooleanField(default=True)),
                ('alive', models.BooleanField(default=True)),
                ('death', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '目标状况',
                'verbose_name_plural': '1.目标状况',
            },
        ),
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(upload_to='', verbose_name='文件')),
            ],
            options={
                'verbose_name': '文件上传',
                'verbose_name_plural': '2.文件上传',
            },
        ),
    ]
