# Generated by Django 3.1.1 on 2020-09-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='is_send',
            field=models.BooleanField(default=True, verbose_name='是否发送'),
        ),
    ]
